# Generated by Django 3.2 on 2021-04-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ba_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
